# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42ad4932f677755af75bf03f1e59b76a1747818988428e516f475e68ab97ef84229652bca12595a9dacd2f29779defbf39513aa038ed9fd6d9d6e50f8261b8f0

test:
  secret_key_base: e44a46f82af75b022850cd9edd5a3ef6a9aa6915f7f50c184456965a202faa71d11e375eb572cda608dfa498277ab5a4fc91cdd14e970976d68a13cdc351343a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
